version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/node:16.20.0

jobs:
  build-and-push:
    executor: docker-executor
    steps:
      - checkout

     
      - run:
          name: Build Docker image
          command: |
            docker build -t laksh061/my-service:latest .

      - run:
          name: Log in to Docker Hub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - run:
          name: Push Docker image
          command: docker push laksh061/my-service:latest

workflows:
  build:
    jobs:
      - build-and-push
